version: '3.8'

services:

  api:
    container_name: app_api
    build: ./app_api
    ports:
      - 3003:3003
    env_file:
      - ./app_api/.env
    volumes:
      - ./app_api:/api
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: database
    ports:
      - 27021:27021
    command: --port 27021
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongodb_data:
    driver: local